version: "3.7"

services:
  php-apache:
    build:
      context: '.'
      dockerfile: 'php-apache.Dockerfile'
    depends_on:
      - mariadb
    user: 1000:1000
    volumes:
      - ../cache/:/var/www/html/cache
      - ./:/var/www/html
    ports:
      - '8000:80'

  mariadb:
    image: 'mariadb'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: videodb
      MYSQL_USER: videodb
      MYSQL_PASSWORD: videodb
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '3306:3306'

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - '7777:8080'