version: "3.7"

services:
  php-apache:
    restart: always
    build:
      context: '.'
      dockerfile: 'php-apache.Dockerfile'
    depends_on:
      - mariadb
    user: 1000:1000
    volumes:
      - ../cache/:/var/www/html/cache
      - ./:/var/www/html
    ports:
      - '8000:80'

  mariadb:
    image: 'mariadb'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: videodb
      MYSQL_USER: videodb
      MYSQL_PASSWORD: videodb
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '3306:3306'

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - '7777:8080'

  liquibase:
    image: liquibase/liquibase
    container_name: liquibase
    depends_on:
      - mariadb
    volumes:
      - ./liquibase:/liquibase/changelog
    command: 'update --defaults-file=/liquibase/changelog/liquibase.properties'

#    command: ['--defaults-file=/liquibase/changelog/liquibase.properties',
#              '--changelog-file=/liquibase/changelog/root-changelog2.xml',
#               '--exclude-objects="videodb_cache',
#               '--diff-types=catalogs,checkconstraints,columns,data,databasepackage,databasepackagebody,foreignkeys,
#                  indexes,primarykeys,schema,sequences,storedprocedures,tables,uniqueconstraints,views',
#              'generate-changelog']

#    command: 'drop-all --defaults-file=/liquibase/changelog/liquibase.properties'